In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df=pd.read_csv("netflix_clean.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,day_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Not Mentioned,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,9,25
1,s2,TV Show,Blood & Water,unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,9,24
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",not Available,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,9,24
3,s4,TV Show,Jailbirds New Orleans,unknown,Not Mentioned,not Available,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,9,24
4,s5,TV Show,Kota Factory,unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,9,24

In [3]:
release_years=df['release_year'].to_numpy()

In [6]:
# mean
avg_year=np.mean(release_years)
print(f'average release year : {avg_year}')

average release year : 2014.183162684869

In [8]:
# median
median_year=np.median(release_years)
print(f'average release year : {median_year}')

average release year : 2017.0

In [9]:
std_year=np.std(release_years)
print(f'std year: {std_year}')

std year: 8.82496399666094

In [10]:
print("Oldest Release Year :", np.min(release_years))
print("Newest Release Year :", np.max(release_years))

Oldest Release Year : 1925
Newest Release Year : 2021

In [11]:
release_range = np.ptp(release_years)

print("Range:", release_range)

Range: 96

In [17]:
recent_content = np.sum(release_years >= 2015)

print("Content Released After 2015:", recent_content)

Content Released After 2015: 6207

In [19]:
total_titles = len(df)

print("Total Titles:", total_titles)
total_movies = df[df["type"] == "Movie"].shape[0]

print("Total Movies:", total_movies)
total_tvshows = df[df["type"] == "TV Show"].shape[0]

print("Total TV Shows:", total_tvshows)

Total Titles: 8790
Total Movies: 6126
Total TV Shows: 2664

In [22]:
kpi = pd.DataFrame({
    "Metric": [
        "Total Titles",
        "Movies",
        "TV Shows",
        "Countries",
        "Directors"
    ],
    "Value": [
        len(df),
        df[df["type"] == "Movie"].shape[0],
        df[df["type"] == "TV Show"].shape[0],
        df["country"].nunique(),
        df["director"].nunique()
    ]
})

kpi

         Metric  Value
0  Total Titles   8790
1        Movies   6126
2      TV Shows   2664
3     Countries    749
4     Directors   4527